### ISSUE TITLE
Numerapi.submission_status() has been updated so numerox.upload_status() is broken

### ISSUE THREAD

**Issue by jmnum** [numerai/numerox#47]
Submission still works however.

**Comment by BouweCeunen** [comment]
Is it the same message as this one: `Upload exception - submission_status() got multiple values for argument 'model_id'`?

**Comment by BouweCeunen** [comment]
I made a PR. You can include the fork directly in your requirements file if you like.
```
git+git://github.com/BouweCeunen/numerox.git#egg=numerox
```

**Comment by jmnum** [comment]
Thank you! It's exactly that.

**Comment by jmnum** [comment]
Fixed in 4.1.7
