### ISSUE TITLE
Update for nomi required

### ISSUE THREAD

**Issue by jrathgeber** [numerai/numerox#50]
Hello,

Could we get an update for the new target Nomi ? 

Numerox checks the contest name vs a static list that it maintains. 

Nomi is not in the list and thus the upload fails. 

Looks like I am the last person using this. Oh no. I am working on something new.

In mean time : 

File "C:\ProgramData\Anaconda3\lib\site-packages\numerox\tournament.py", line 101, in tournament_str2int
    raise ValueError('`tournament_str` name not recognized')

![image](https://user-images.githubusercontent.com/10384129/99741773-07dd2700-2aa0-11eb-9ea5-e9da4c75e0a9.png)

**Comment by suud** [comment]
The problem isn't the tournament name, but that some column names have been updated. See Pull Request #49 for more details.

**Comment by jrathgeber** [comment]
Ok. It is possible numerox does more than what I use it for. I only make use of the download and upload data functions. I have my own model that generates the prediction file. I was able to update that myself easily as it is my own code. But I use numerox to upload the file to numerai. That last step is failing because it takes tournament name as a parameter and checks it. Hense I am keen to add nomi to above list. This is not urgent, it just means I have to upload file myself each week :) When the whole thing is fixed I will have a fully automated process again.

**Comment by jrathgeber** [comment]
I am pleased this issue was updated and marked as closed. Thank you. 

Any chance we could do a release now ? This would increment the version number to 4.1.8 and ideally trigger a push to the python package manager. Thank you. Not sure what is involved exactly or how much work this is.

**Comment by pschork** [comment]
@jrathgeber pypi updated

**Comment by jrathgeber** [comment]
thank you
